# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js LTS image as the base
FROM node:18-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install app dependencies
RUN npm install

# Copy app source code
COPY . .

# Build the application
RUN npm run build

# Use Node.js LTS image for production
FROM node:18-alpine AS production

# Create app directory
WORKDIR /app

# Copy only necessary files for production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

# Expose the application's port
EXPOSE 3000

# Start the application
CMD ["node", "dist/main.js"]
